version: 0.2

phases:
  pre_build:
    commands:
      - echo Deployment started on `date`
      - rm -rf ./public
      - echo I am exiting pre_build
  build:
    commands:
      - echo I got to the build stage
      - packaging static files to public folder
      - npm run build
      - echo Syncing S3 Content
      - aws s3 sync ./public/browser s3://dev.eventapp.com
      - echo exiting the build stage
  post_build:
    commands:
      - echo Deployment completed on `date`
