version: 0.2

phases:
  pre_build:
    commands:
      - echo Deployment started on `date`
      - rm -rf ./public
      - echo I am exiting pre_build
  build:
    commands:
      - echo I got to the build stage
      - npm install -g @angular/cli # Install Angular CLI globally
      - npm install # Install project dependencies
      - npm run build
      - echo Deleting old content in S3 bucket
      - aws s3 rm s3://prod.eventapp.com --recursive # Delete all content in the S3 bucket
      - echo Syncing new content to S3 bucket
      - aws s3 sync ./public/browser s3://prod.eventapp.com
      - echo Exiting the build stage
  post_build:
    commands:
      - echo Deployment completed on `date`
